Add CUDA 11.8 images
conda-forge/docker-images pull request #217
Opened 2022-10-04 21:50 UTC by m3vaz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2022-10-04 21:58 UTC, jaimergp commented on .github/workflows/ci.yaml
> +          DOCKERIMAGE: linux-anvil-cuda
```suggestion
        - DOCKERIMAGE: linux-anvil-cuda
```

2022-10-04 22:15 UTC, m3vaz commented
@conda-forge-admin, please rerender

2022-10-04 22:30 UTC, jaimergp commented
There's an error I am working on at #220. Stay tuned :)

2022-10-16 20:48 UTC, leofang commented
@conda-forge-admin, please restart ci

2022-10-16 20:48 UTC, leofang commented
oh this repo probably does not have the bot set up..

2022-10-16 22:02 UTC, hmaarrfk commented
i thought we were to support to wait to move on this cc @beckermr

2022-10-16 23:45 UTC, beckermr commented
Yes do not merge.

2022-10-16 23:45 UTC, beckermr requested changes
Do not merge.

2022-10-19 20:43 UTC, m3vaz commented
From internal discussion, closing until further notice.

2022-10-19 20:43 UTC, closed without merging